# This is a sample tokenization configuration with all values set to their default.
#
# See the Tokenizer documentation for a complete list and description of available
# options:
#
# https://github.com/OpenNMT/Tokenizer/blob/master/docs/options.md

mode: conservative

bpe_model_path: ""
bpe_model_path: ""
bpe_vocab_threshold: 50

sp_model_path: ""

joiner: ￭
joiner_annotate: false
joiner_new: false

spacer_annotate: false
spacer_new: false

preserve_placeholders: false

segment_case: false
segment_numbers: false
segment_alphabet_change: false
segment_alphabet: []

no_substitution: false

# (unsupported) Casing features is currently unsupported.
case_feature: false
