language: python
python:
  - "2.7"
env:
  global:
    - LATEST_TF_VERSION="1.15.*"
  matrix:
    - TF_VERSION="1.12.*"
    - TF_VERSION="1.13.*"
    - TF_VERSION="1.14.*"
    - TF_VERSION="$LATEST_TF_VERSION"
before_install:
  - pip install tensorflow==$TF_VERSION
  - pip install -e .[tests]
before_script:
  - wget https://s3.amazonaws.com/opennmt-models/transliteration-aren.tar.gz
  - mkdir -p $TRAVIS_BUILD_DIR/testdata
  - tar xf transliteration-aren.tar.gz -C $TRAVIS_BUILD_DIR/testdata
script:
  - nose2
matrix:
  include:
    - python: "3.6"
      env:
        - TF_VERSION="$LATEST_TF_VERSION"
      install:
        - pip install pylint==2.2.* wheel twine
      script:
        - nose2
        - pylint opennmt/
      after_success:
        - |
              if [[ -n $TRAVIS_TAG ]]; then
                  python setup.py sdist bdist_wheel --universal
                  twine upload dist/*
              fi
